Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,7 +18,12 @@ jobs:
         run: sudo apt-get install -y aria2
 
       - name: Download file
-        run: aria2c -o /tmp/largefile.ext "https://filehippo.com/download-launch/fifa-12/windows/?dt=internalDownload&token=RAvvK7CNFamPi1fsBO1U9FirlBjpIWtX2dL150yTFt0"
+        run: |
+          aria2c -o /tmp/largefile.ext "https://filehippo.com/download-launch/fifa-12/windows/?dt=internalDownload&token=RAvvK7CNFamPi1fsBO1U9FirlBjpIWtX2dL150yTFt0"
+          if [ ! -f /tmp/largefile.ext ]; then
+            echo "Error: File /tmp/largefile.ext not found!"
+            exit 1
+          fi
 
       - name: Install Git LFS
         run: |
